# Generated by Django 4.0.2 on 2022-02-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='gname',
        ),
    ]
